extends: airbnb
env:
  node: true
plugins:
  - react
  - jsx-a11y
  - import
rules:
  strict: 0
  global-require: 0
  key-spacing:
    - error
    - align: value
  no-multi-spaces:
    - error
    - exceptions:
        VariableDeclarator: true
  no-unused-vars:
    - error
    - argsIgnorePattern: "next"
  no-params-reassign:
    - error
    - props: false
  no-console: 0
