-- INSERT INTO puzzles (name, url) VALUES ('Puzzle 1', 'url(http://i.imgur.com/B8xsff4.jpg?4)');
-- INSERT INTO puzzles (name, url) VALUES ('Puzzle 2', 'url(http://i.imgur.com/b5gcmnR.jpg?2)');
-- INSERT INTO puzzles (name, url) VALUES ('Puzzle 3', 'url(http://i.imgur.com/CWvP6zh.jpg?3)');
-- INSERT INTO puzzles (name, url) VALUES ('Puzzle 4', 'url(http://i.imgur.com/wxiGxy4.jpg?2)');
-- INSERT INTO puzzles (name, url) VALUES ('Puzzle 5', 'url(http://i.imgur.com/mGOb37s.jpg?2)');
INSERT INTO puzzles (name, url) VALUES ('Puzzle 6', 'url(http://i.imgur.com/CB0DiJ0.jpg?1)');
INSERT INTO puzzles (name, url) VALUES ('Puzzle 7', 'url(http://i.imgur.com/csQNW88.jpg?1)');
INSERT INTO puzzles (name, url) VALUES ('Puzzle 8', 'url(http://i.imgur.com/aBHrLnf.jpg?2)');
INSERT INTO puzzles (name, url) VALUES ('Puzzle 9', 'url(http://i.imgur.com/myj9KwV.jpg?1)');
INSERT INTO puzzles (name, url) VALUES ('Puzzle 10', 'url(http://i.imgur.com/8c6bicg.jpg?1)');
INSERT INTO puzzles (name, url) VALUES ('Puzzle 11', 'url(http://i.imgur.com/9cR1z7L.jpg?1)');
INSERT INTO puzzles (name, url) VALUES ('Puzzle 12', 'url(http://i.imgur.com/UGtZFhY.jpg?1)');
INSERT INTO puzzles (name, url) VALUES ('Puzzle 13', 'url(http://i.imgur.com/kK5lz2s.jpg?1)');
INSERT INTO puzzles (name, url) VALUES ('Puzzle 14', 'url(http://i.imgur.com/dzj0cfV.jpg?1)');
INSERT INTO puzzles (name, url) VALUES ('Puzzle 15', 'url(http://i.imgur.com/WTfFodP.jpg?1)');
INSERT INTO puzzles (name, url) VALUES ('Puzzle 16', 'url(http://i.imgur.com/oebBjiq.jpg?1)');
INSERT INTO puzzles (name, url) VALUES ('Puzzle 17', 'url(http://i.imgur.com/HHNJgI4.jpg?1)');
INSERT INTO puzzles (name, url) VALUES ('Puzzle 18', 'url(http://i.imgur.com/78E3bq8.jpg?1)');
INSERT INTO puzzles (name, url) VALUES ('Puzzle 19', 'url(http://i.imgur.com/j9ZGSEo.jpg?1)');
INSERT INTO puzzles (name, url) VALUES ('Puzzle 20', 'url(http://i.imgur.com/4tHIBRd.jpg?1)');
INSERT INTO puzzles (name, url) VALUES ('Puzzle 21', 'url(http://i.imgur.com/8DdNP7D.jpg?1)');
INSERT INTO puzzles (name, url) VALUES ('Puzzle 22', 'url(http://i.imgur.com/tCsEvH1.jpg?1)');
INSERT INTO puzzles (name, url) VALUES ('Puzzle 23', 'url(http://i.imgur.com/t0UZaxh.jpg?1)');
INSERT INTO puzzles (name, url) VALUES ('Puzzle 24', 'url(http://i.imgur.com/ylZqPy0.jpg?1)');
INSERT INTO puzzles (name, url) VALUES ('Puzzle 25', 'url(http://i.imgur.com/XWEwK0t.jpg?1)');
INSERT INTO puzzles (name, url) VALUES ('Puzzle 26', 'url(http://i.imgur.com/YfvBWpt.jpg?1)');
INSERT INTO puzzles (name, url) VALUES ('Puzzle 27', 'url(http://i.imgur.com/2fAB4Dd.jpg?1)');
INSERT INTO puzzles (name, url) VALUES ('Puzzle 28', 'url(http://i.imgur.com/bPE5EGG.jpg?1)');
INSERT INTO puzzles (name, url) VALUES ('Puzzle 29', 'url(http://i.imgur.com/XvW5rbG.jpg?1)');
INSERT INTO puzzles (name, url) VALUES ('Puzzle 30', 'url(http://i.imgur.com/v1PL2vP.jpg?2)');
INSERT INTO puzzles (name, url) VALUES ('Puzzle 31', 'url(http://i.imgur.com/7yaWUPc.jpg?2)');
INSERT INTO puzzles (name, url) VALUES ('Puzzle 32', 'url(http://i.imgur.com/NABahjE.jpg?2)');
INSERT INTO puzzles (name, url) VALUES ('Puzzle 33', 'url(http://i.imgur.com/m5JWcJs.jpg?2)');
INSERT INTO puzzles (name, url) VALUES ('Puzzle 34', 'url(http://i.imgur.com/HWs6Mym.jpg?2)');
INSERT INTO puzzles (name, url) VALUES ('Puzzle 35', 'url(http://i.imgur.com/Saq65n9.jpg?1)');

-- INSERT INTO users (username, password, email) VALUES ('Guest', 'n/a', 'no@email.com');

-- -- INSERT EASY SCORES
-- INSERT INTO scores (score, clock, user_id, puzzle_id, difficulty) VALUES (9999999, 'No Score', 1, 1, 'easy');
-- INSERT INTO scores (score, clock, user_id, puzzle_id, difficulty) VALUES (9999999, 'No Score', 1, 1, 'easy');
-- INSERT INTO scores (score, clock, user_id, puzzle_id, difficulty) VALUES (9999999, 'No Score', 1, 1, 'easy');
-- INSERT INTO scores (score, clock, user_id, puzzle_id, difficulty) VALUES (9999999, 'No Score', 1, 2, 'easy');
-- INSERT INTO scores (score, clock, user_id, puzzle_id, difficulty) VALUES (9999999, 'No Score', 1, 2, 'easy');
-- INSERT INTO scores (score, clock, user_id, puzzle_id, difficulty) VALUES (9999999, 'No Score', 1, 2, 'easy');
-- INSERT INTO scores (score, clock, user_id, puzzle_id, difficulty) VALUES (9999999, 'No Score', 1, 3, 'easy');
-- INSERT INTO scores (score, clock, user_id, puzzle_id, difficulty) VALUES (9999999, 'No Score', 1, 3, 'easy');
-- INSERT INTO scores (score, clock, user_id, puzzle_id, difficulty) VALUES (9999999, 'No Score', 1, 3, 'easy');
-- INSERT INTO scores (score, clock, user_id, puzzle_id, difficulty) VALUES (9999999, 'No Score', 1, 4, 'easy');
-- INSERT INTO scores (score, clock, user_id, puzzle_id, difficulty) VALUES (9999999, 'No Score', 1, 4, 'easy');
-- INSERT INTO scores (score, clock, user_id, puzzle_id, difficulty) VALUES (9999999, 'No Score', 1, 4, 'easy');
-- INSERT INTO scores (score, clock, user_id, puzzle_id, difficulty) VALUES (9999999, 'No Score', 1, 5, 'easy');
-- INSERT INTO scores (score, clock, user_id, puzzle_id, difficulty) VALUES (9999999, 'No Score', 1, 5, 'easy');
-- INSERT INTO scores (score, clock, user_id, puzzle_id, difficulty) VALUES (9999999, 'No Score', 1, 5, 'easy');

-- -- INSERT MEDIUM SCORES
-- INSERT INTO scores (score, clock, user_id, puzzle_id, difficulty) VALUES (9999999, 'No Score', 1, 1, 'medium');
-- INSERT INTO scores (score, clock, user_id, puzzle_id, difficulty) VALUES (9999999, 'No Score', 1, 1, 'medium');
-- INSERT INTO scores (score, clock, user_id, puzzle_id, difficulty) VALUES (9999999, 'No Score', 1, 1, 'medium');
-- INSERT INTO scores (score, clock, user_id, puzzle_id, difficulty) VALUES (9999999, 'No Score', 1, 2, 'medium');
-- INSERT INTO scores (score, clock, user_id, puzzle_id, difficulty) VALUES (9999999, 'No Score', 1, 2, 'medium');
-- INSERT INTO scores (score, clock, user_id, puzzle_id, difficulty) VALUES (9999999, 'No Score', 1, 2, 'medium');
-- INSERT INTO scores (score, clock, user_id, puzzle_id, difficulty) VALUES (9999999, 'No Score', 1, 3, 'medium');
-- INSERT INTO scores (score, clock, user_id, puzzle_id, difficulty) VALUES (9999999, 'No Score', 1, 3, 'medium');
-- INSERT INTO scores (score, clock, user_id, puzzle_id, difficulty) VALUES (9999999, 'No Score', 1, 3, 'medium');
-- INSERT INTO scores (score, clock, user_id, puzzle_id, difficulty) VALUES (9999999, 'No Score', 1, 4, 'medium');
-- INSERT INTO scores (score, clock, user_id, puzzle_id, difficulty) VALUES (9999999, 'No Score', 1, 4, 'medium');
-- INSERT INTO scores (score, clock, user_id, puzzle_id, difficulty) VALUES (9999999, 'No Score', 1, 4, 'medium');
-- INSERT INTO scores (score, clock, user_id, puzzle_id, difficulty) VALUES (9999999, 'No Score', 1, 5, 'medium');
-- INSERT INTO scores (score, clock, user_id, puzzle_id, difficulty) VALUES (9999999, 'No Score', 1, 5, 'medium');
-- INSERT INTO scores (score, clock, user_id, puzzle_id, difficulty) VALUES (9999999, 'No Score', 1, 5, 'medium');

-- -- INSERT HARD SCORES
-- INSERT INTO scores (score, clock, user_id, puzzle_id, difficulty) VALUES (9999999, 'No Score', 1, 1, 'hard');
-- INSERT INTO scores (score, clock, user_id, puzzle_id, difficulty) VALUES (9999999, 'No Score', 1, 1, 'hard');
-- INSERT INTO scores (score, clock, user_id, puzzle_id, difficulty) VALUES (9999999, 'No Score', 1, 1, 'hard');
-- INSERT INTO scores (score, clock, user_id, puzzle_id, difficulty) VALUES (9999999, 'No Score', 1, 2, 'hard');
-- INSERT INTO scores (score, clock, user_id, puzzle_id, difficulty) VALUES (9999999, 'No Score', 1, 2, 'hard');
-- INSERT INTO scores (score, clock, user_id, puzzle_id, difficulty) VALUES (9999999, 'No Score', 1, 2, 'hard');
-- INSERT INTO scores (score, clock, user_id, puzzle_id, difficulty) VALUES (9999999, 'No Score', 1, 3, 'hard');
-- INSERT INTO scores (score, clock, user_id, puzzle_id, difficulty) VALUES (9999999, 'No Score', 1, 3, 'hard');
-- INSERT INTO scores (score, clock, user_id, puzzle_id, difficulty) VALUES (9999999, 'No Score', 1, 3, 'hard');
-- INSERT INTO scores (score, clock, user_id, puzzle_id, difficulty) VALUES (9999999, 'No Score', 1, 4, 'hard');
-- INSERT INTO scores (score, clock, user_id, puzzle_id, difficulty) VALUES (9999999, 'No Score', 1, 4, 'hard');
-- INSERT INTO scores (score, clock, user_id, puzzle_id, difficulty) VALUES (9999999, 'No Score', 1, 4, 'hard');
-- INSERT INTO scores (score, clock, user_id, puzzle_id, difficulty) VALUES (9999999, 'No Score', 1, 5, 'hard');
-- INSERT INTO scores (score, clock, user_id, puzzle_id, difficulty) VALUES (9999999, 'No Score', 1, 5, 'hard');
-- INSERT INTO scores (score, clock, user_id, puzzle_id, difficulty) VALUES (9999999, 'No Score', 1, 5, 'hard');

-- -- INSERT EXPERT SCORES
-- INSERT INTO scores (score, clock, user_id, puzzle_id, difficulty) VALUES (9999999, 'No Score', 1, 1, 'expert');
-- INSERT INTO scores (score, clock, user_id, puzzle_id, difficulty) VALUES (9999999, 'No Score', 1, 1, 'expert');
-- INSERT INTO scores (score, clock, user_id, puzzle_id, difficulty) VALUES (9999999, 'No Score', 1, 1, 'expert');
-- INSERT INTO scores (score, clock, user_id, puzzle_id, difficulty) VALUES (9999999, 'No Score', 1, 2, 'expert');
-- INSERT INTO scores (score, clock, user_id, puzzle_id, difficulty) VALUES (9999999, 'No Score', 1, 2, 'expert');
-- INSERT INTO scores (score, clock, user_id, puzzle_id, difficulty) VALUES (9999999, 'No Score', 1, 2, 'expert');
-- INSERT INTO scores (score, clock, user_id, puzzle_id, difficulty) VALUES (9999999, 'No Score', 1, 3, 'expert');
-- INSERT INTO scores (score, clock, user_id, puzzle_id, difficulty) VALUES (9999999, 'No Score', 1, 3, 'expert');
-- INSERT INTO scores (score, clock, user_id, puzzle_id, difficulty) VALUES (9999999, 'No Score', 1, 3, 'expert');
-- INSERT INTO scores (score, clock, user_id, puzzle_id, difficulty) VALUES (9999999, 'No Score', 1, 4, 'expert');
-- INSERT INTO scores (score, clock, user_id, puzzle_id, difficulty) VALUES (9999999, 'No Score', 1, 4, 'expert');
-- INSERT INTO scores (score, clock, user_id, puzzle_id, difficulty) VALUES (9999999, 'No Score', 1, 4, 'expert');
-- INSERT INTO scores (score, clock, user_id, puzzle_id, difficulty) VALUES (9999999, 'No Score', 1, 5, 'expert');
-- INSERT INTO scores (score, clock, user_id, puzzle_id, difficulty) VALUES (9999999, 'No Score', 1, 5, 'expert');
-- INSERT INTO scores (score, clock, user_id, puzzle_id, difficulty) VALUES (9999999, 'No Score', 1, 5, 'expert');
